### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by m-4morim** [fernando-r-costa/Form-interativo-cadastro-cartoes#1]
Fernando, já realizei alguns desafios do Frontend Mentor, mas não aproveitei o Readme que vem nos arquivos base. Eu sempre acabei criando um novo.
Pelo que percebi, ele já vem configurado para que ao clique a tela seja direcionada ao índice?

**Comment by fernando-r-costa** [comment]
E aí Marcos, desculpa a demora. Olha eu não aproveitei  100% do readme que veio, apaguei algumas coisas, mas achei bem legal e por sugestão de um tutor vou passar a usar como template.
O readme é escrito em markdown, que é uma linguagem de marcação, como HTML, bem simples, mas ainda não estudei para aprender mais. 
Sei que para fazer links usa-se a seguinte sequencia: abre chaves + coloca o texto do link + fecha chaves + abre parenteses + link + fecha parenteses. Para índice você tem que usar # no link e também tem que ter feito essa marcação no índice, para link externo basta colocar a url.
Tamo juntos pro que precisar!
